name: "Require matching Dummy‑AIQ PR"

on:
  pull_request:
    branches:
      - dummy-main  

jobs:
  check-feature-pr:
    if: github.event.pull_request.base.ref == 'dummy-main'
    runs-on: ubuntu-latest
    steps:
      - name: Check for matching PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const headBranch = pr.head.ref;      // e.g. "feature/awesome-change"
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            
            const { data: companionPRs } = await github.rest.pulls.list({
              owner,
              repo,
              state: "all",                     // or "open" if you only care about active ones
              base: "aiq-workflow-migration",   // feature branch
              head: `${owner}:${headBranch}`,   // exactly that same branch in your fork/org
            });
            
            if (companionPRs.length === 0) {
              core.setFailed(
                `No companion PR into 'aiq-workflow-migration' from branch '${headBranch}'.`
              );
            }
        
